export  const kamigamis = [
      { number: 01,
        emoji: "🌞",
        name: "天照大神 あまてらすおおみかみ", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 02,
        emoji: "",
        name: "須佐之男命 すさのお", image: "./kamigami/02.png",
        keyword: "",
        message: ""
      },
      { number: 03,
        emoji: "📖",
        name: "思金神 おもいかね", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 04,
        emoji: "💃",
        name: "天宇受売命 あめのうずめ", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 05,
        emoji: "",
        name: "大国主命 おおくにぬし", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 06,
        emoji: "",
        name: "少彦名命 すくなびこな", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 07,
        emoji: "",
        name: "瓊瓊杵尊 ににぎ", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 08,
        emoji: "👺",
        name: "猿田彦大神 さるたひこ", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 09,
        emoji: "🌸",
        name: "木花咲耶姫命 このはなさくやひめ", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 10,
        emoji: "⚔",
        name: "日本武尊 やまとたける", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 11,
        emoji: "🐉",
        name: "龍神 りゅうじん", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 12,
        emoji: "💰",
        name: "七福神 しちふくじん", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 13,
        emoji: "",
        name: "達磨 だるま", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 14,
        emoji: "⛩",
        name: "狛犬 こまいぬ", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 15,
        emoji: "🐈",
        name: "招き猫 まねきねこ", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 16,
        emoji: "",
        name: "お地蔵様 おじぞうさま", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 17,
        emoji: "",
        name: "不動明王 ふどうみょうおう", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 18,
        emoji: "❤",
        name: "観音菩薩 かんのんぼさつ", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 19,
        emoji: "",
        name: "厄除け大師 やくよけだいし", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 20,
        emoji: "",
        name: "大仏様 だいぶつさま", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 21,
        emoji: "🌕",
        name: "月読命 つくよみ", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 22,
        emoji: "🗾",
        name: "伊邪那岐命・伊邪那美命 いざなぎ・いざなみ", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 23,
        emoji: "",
        name: "住吉大神 すみよしたいじん", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 24,
        emoji: "🛣",
        name: "宗像三女神 むなかたさんじょしん", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 25,
        emoji: "🌾",
        name: "宇迦之御魂命 うかのみたま", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 26,
        emoji: "",
        name: "大山咋神 おおやまくい", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 27,
        emoji: "",
        name: "菊理媛神 くくりひめ", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 28,
        emoji: "",
        name: "建御雷神 たけみかづち", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 29,
        emoji: "",
        name: "建御名方神 たけみなかた", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 30,
        emoji: "🕊",
        name: "八幡様 はちまん", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
      { number: 31,
        emoji: "👓",
        name: "天神様 てんじん", image: "./kamigami/01.png",
        keyword: "",
        message: ""
      },
    ];
